'use client';

import { MetricBar } from './MetricBar';
import Image from 'next/image';
import { ReportService } from '@/services/ReportService';
import { css } from 'styled-components';

interface ReportMetric {
    label: string;
    value: number;
    tooltipContent?: string;
    color?: 'primary' | 'warning' | 'danger' | 'success';
}

interface ReportTemplateProps {
    title: string;
    date: string;
    companyName: string;
    metrics: ReportMetric[];
    summary: string;
    recommendations: string[];
}

export const ReportTemplate = ({
    title,
    date,
    companyName,
    metrics,
    summary,
    recommendations
}: ReportTemplateProps) => {
    const handleDownload = async () => {
        try {
            await ReportService.downloadPDF({
                title,
                companyName,
                metrics,
                summary,
                recommendations,
            });
        } catch (error) {
            console.error('Failed to download PDF:', error);
            // You can add toast notification here
        }
    };

    return (
        <div className="max-w-4xl mx-auto bg-white">
            {/* Header */}
            <header className="py-8 px-6 border-b border-gray-200 print:border-gray-400">
                <div className="flex justify-between items-center">
                    <div>
                        <h1 className="text-2xl font-pretendard font-bold text-gray-900">{title}</h1>
                        <p className="mt-1 text-sm text-gray-500">{date}</p>
                    </div>
                    <div className="text-right">
                        <p className="font-pretendard font-medium text-gray-900">{companyName}</p>
                        <p className="mt-1 text-sm text-gray-500">Generated by Trae AI</p>
                    </div>
                    <button
                        onClick={handleDownload}
                        className="download-button"
                    >
                        Download PDF
                    </button>
                </div>
            </header>

            {/* Main Content */}
            <main className="py-8 px-6">
                {/* Metrics Section */}
                <section className="mb-8">
                    <h2 className="text-xl font-pretendard font-semibold text-gray-900 mb-4">주요 지표</h2>
                    <div className="space-y-4 md:space-y-6">
                        {metrics.map((metric, index) => (
                            <MetricBar
                                key={index}
                                label={metric.label}
                                value={metric.value}
                                tooltipContent={metric.tooltipContent}
                                color={metric.color}
                            />
                        ))}
                    </div>
                </section>

                {/* Summary Section */}
                <section className="mb-8">
                    <h2 className="text-xl font-pretendard font-semibold text-gray-900 mb-4">요약</h2>
                    <div className="bg-gray-50 rounded-lg p-6">
                        <p className="text-gray-700 whitespace-pre-line">{summary}</p>
                    </div>
                </section>

                {/* Recommendations Section */}
                <section className="mb-8">
                    <h2 className="text-xl font-pretendard font-semibold text-gray-900 mb-4">권장 사항</h2>
                    <div className="bg-white border border-gray-200 rounded-lg divide-y divide-gray-200">
                        {recommendations.map((recommendation, index) => (
                            <div key={index} className="p-4 flex items-start">
                                <span className="flex-shrink-0 w-6 h-6 flex items-center justify-center rounded-full bg-indigo-100 text-indigo-600 mr-3">
                                    {index + 1}
                                </span>
                                <p className="text-gray-700">{recommendation}</p>
                            </div>
                        ))}
                    </div>
                </section>
            </main>

            {/* Footer */}
            <footer className="py-6 px-6 border-t border-gray-200 print:border-gray-400">
                <div className="flex justify-between items-center text-sm text-gray-500">
                    <p>© {new Date().getFullYear()} Trae AI. All rights reserved.</p>
                    <p>Page 1 of 1</p>
                </div>
            </footer>

            {/* Print Styles */}
            <style jsx global>{`
                @media print {
                    @page {
                        margin: 0.5in;
                    }
                    body {
                        print-color-adjust: exact;
                        -webkit-print-color-adjust: exact;
                    }
                    .print\\:border-gray-400 {
                        border-color: #9ca3af !important;
                    }
                }
                @media screen and (max-width: 640px) {
                    .md\\:space-y-6 > * + * {
                        margin-top: 1.5rem;
                    }
                }

                .download-button {
                    position: absolute;
                    top: 1rem;
                    right: 1rem;
                    padding: 0.5rem 1rem;
                    background-color: #0070f3;
                    color: white;
                    border: none;
                    border-radius: 4px;
                    cursor: pointer;
                    font-weight: 500;
                    transition: background-color 0.2s;

                    &:hover {
                        background-color: #0051cc;
                    }

                    &:active {
                        background-color: #003da6;
                    }
                }

                @media print {
                    .download-button {
                        display: none;
                    }
                }
            `}</style>
        </div>
    );
}; 